client_config_backend: settings
client_config:
  client_id: 852076654829-1n09rsi8dsngsccp9tgll3k8qn6tfhjq.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json
get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
